#!/bin/bash

##
#
# This is example script to use Cohesity Remote Adapter feature to backup MySQL databases
#
##

trap "exit 1" HUP INT TERM
PATH=/sbin:/bin:/usr/sbin:/usr/bin

BACKUP_DIR=/backup
LOG_DIR="$BACKUP_DIR/log"
TODAY=$(date +"%m-%d-%Y")
MYSQL="$(which mysql)"
MYSQLDUMP="$(which mysqldump)"
GZIP="$(which gzip)"
MYSQL_USER="username"
MYSQL_PASSWORD="password"
MYSQL_HOST="localhost"
NFS_MOUNT=("/mnt/cohesity1" "/mnt/cohesity2" "/mnt/cohesity3" "/mnt/cohesity4")
SPLIT_SIZE=4
BACKUP_RETAIN_DAYS=7

# Create directory for todays backup and logs
mkdir -p $BACKUP_DIR/$TODAY
mkdir -p $LOG_DIR/$TODAY

if [ -d $BACKUP_DIR/$TODAY ]; then

        # Get all database list first
        DBS="$($MYSQL -u $MYSQL_USER -h $MYSQL_HOST -p$MYSQL_PASSWORD -Bse 'show databases')"

        for db in $DBS
        do
            mkdir -p $BACKUP_DIR/$TODAY/$db
            $MYSQLDUMP --single-transaction  -u $MYSQL_USER -h $MYSQL_HOST -p$MYSQL_PASSWORD $db | $GZIP -9 > $BACKUP_DIR/$TODAY/$db/$db.dump.gz
        done
fi

# Find backups to transaction log and split logs to size of $SPLIT_SIZE

find $BACKUP_DIR/$TODAY/* -type d > $LOG_DIR/$TODAY/transaction.log
touch $LOG_DIR/$TODAY/rsync.log

cd $LOG_DIR/$TODAY
split -l$SPLIT_SIZE -d $LOG_DIR/$TODAY/transaction.log folders_part

# Build rsync job
for files in `ls -B $LOG_DIR/$TODAY/folders_part*`
do
    TARGET_NFS=${NFS_MOUNT[RANDOM%${#NFS_MOUNT[@]}]}
    echo "rsync -avzm --relative --stats --safe-links --ignore-existing --human-readable \`cat $files\`  $TARGET_NFS" >> $LOG_DIR/$TODAY/runjob.sh
done

. $LOG_DIR/$TODAY/runjob.sh

# Remove old backups from view
DBDELDATE=`date +"%m-%d-%Y" --date="${BACKUP_RETAIN_DAYS} days ago"`

if [ ! -z ${BACKUP_DIR} ]; then
      cd ${BACKUP_DIR}
      if [ ! -z ${DBDELDATE} ] && [ -d ${DBDELDATE} ]; then
            rm -rf ${DBDELDATE}
      fi
fi 

# Clean backup scripts and file lists
rm -rf $LOG_DIR/$TODAY/runjob.sh
rm -rf $LOG_DIR/$TODAY/folders_part*

exit 0
